### ISSUE TITLE
Can't open the Program

### ISSUE THREAD

**Issue by AzuraDelaRochelle** [dayjaby/yomisama#12]
Hello..

I received a message of errors when I want to install this one.

Thanks a lot.

**Comment by dayjaby** [comment]
Which error message did you get? What did you do to install Yomisama?

**Comment by AzuraDelaRochelle** [comment]
<a href='https://www.casimages.com/i/20090105460710009.png.html' title='Mon image'>Lien vers mon image</a>

**Comment by dayjaby** [comment]
Which version of Anki are you using? I will try to add support for versions 2.1.28 to 2.1.39.

**Comment by AzuraDelaRochelle** [comment]
How to know ?

**Comment by dayjaby** [comment]
In Anki: Help > About

**Comment by AzuraDelaRochelle** [comment]
[image: image.png]

**Comment by dayjaby** [comment]
I cant see the image ^^

**Comment by AzuraDelaRochelle** [comment]
Version 2.1.35 (84dcaa86)
Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

**Comment by dayjaby** [comment]
Ok, you can try to install again. I set the compatible versions to 2.1.28-39

**Comment by AzuraDelaRochelle** [comment]
I received that :

site de support du greffon <https://help.ankiweb.net/discussions/add-ons/>

Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

Platform: Windows 10

Flags: frz=True ao=True sv=1

Add-ons, last update check: 2021-02-06 14:33:12


Caught exception:

Traceback (most recent call last):

File
"C:\Users\Adhéna\AppData\Roaming\Anki2\addons21\907186589\yomi_base\reader.py",
line 368, in inner

self.plugin.loadLanguage(language,callback=None)

File
"C:\Users\Adhéna\AppData\Roaming\Anki2\addons21\907186589\yomi_base\yomichan.py",
line 47, in loadLanguage

module = languages[language]

KeyError: 'french'



When I try to work the Yomisama :


[image: image.png]

**Comment by dayjaby** [comment]
Were you trying to add french as a language? At the moment these languages are supported:

Japanese, Chinese

I had to drop the support for these as Anki switched from python2 to 3:

Korean, German, Spanish

**Comment by AzuraDelaRochelle** [comment]
No. I am an French speaker. But I have not idea about what I can do, or
can't do. Maybe I could use the English for studying ? That would be not a
problem really.
