### ISSUE TITLE
Add-on Startup Failed

### ISSUE THREAD

**Issue by Kirchheim** [dayjaby/yomisama#13]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

When loading Yomisama JapaneseChinese:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/maikbraun/Library/Application Support/Anki2/addons21/907186589/__init__.py", line 4, in <module>
    from PyQt5 import QtGui, QtCore
ModuleNotFoundError: No module named 'PyQt5'

**Comment by dayjaby** [comment]
Hey, thanks for testing out Yomisama! Can you try `pip install PyQt5` for now? If that still doesn't work for you, I will do an update so that it uses the same Qt version as Anki itself.

**Comment by Kirchheim** [comment]
Hi, 

I get the following response

￼

Am 05.07.2024 um 18:41 schrieb David Jablonski ***@***.***>:


Hey, thanks for testing out Yomisama! Can you try pip install PyQt5 for now? If that still doesn't work for you, I will do an update so that it uses the same Qt version as Anki itself.

**Comment by dayjaby** [comment]
![image](https://github.com/dayjaby/yomisama/assets/164396/ce4807e9-64a5-435c-9ad3-15fcacc0111b)

Please install this version of Anki. Anki based on Qt6 is not and will not be supported - would be too much time for me to adapt the entire code to another Qt version.
