### ISSUE TITLE
Fix invalid copyrights notices

### ISSUE THREAD

**Issue by FooSoft** [dayjaby/yomisama#5]
Hey, I noticed that in [this commit](https://github.com/dayjaby/yomisama/commit/c8145df9299dbe1398f9447b5e6a7e54e7c1ae5d) you removed my name from copyright notices (even from files that you have not touched). This isn't a cool thing to do (forking a project does not transfer IP ownership). The correct way to attribute credit on files you have contributed to is by listing multiple authors. Obviously, this is not needed on new source files you have added to the project.

**Comment by dayjaby** [comment]
Hi Alex,

thanks for letting me know! I have zero experience with
copyrights/licenses; so forgive me :) Will revert that change the next time
I am going to commit something.

Cheers,
David
