### ISSUE TITLE
Breaks filtered decks

### ISSUE THREAD

**Issue by ghost** [dayjaby/yomisama#7]
Hi. While Yomisama is enabled, I can't build any filtered decks.

Version 2.1.22 (0ecc189a)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Windows 10

**Comment by dayjaby** [comment]
I will have a look into this. Thanks for posting!

**Comment by dayjaby** [comment]
Hey, can you check the latest version? https://ankiweb.net/shared/info/907186589 building filtered decks from Yomisama decks works at least for me.
